// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/puntos": {
            "get": {
                "description": "Obtiene puntos de donación recomendados dentro de un radio.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "puntos"
                ],
                "summary": "Obtiene puntos de donación dentro de un radio",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Coordenadas en formato JSON",
                        "name": "coordenadas",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Radio en metros",
                        "name": "radio",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.PuntoDeDonacionResult"
                            }
                        }
                    },
                    "400": {
                        "description": "Parámetros inválidos",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "No se encontraron puntos de donación en el radio especificado",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Crea un nuevo punto de donación",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "puntos"
                ],
                "summary": "Crea un nuevo punto de donación",
                "parameters": [
                    {
                        "description": "Punto de Donación",
                        "name": "punto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PuntoDeDonacion"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.PuntoDeDonacion"
                        }
                    },
                    "400": {
                        "description": "Error al crear el punto de donación",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/puntos/{id}": {
            "delete": {
                "description": "Elimina un punto de donación de la base de datos.",
                "tags": [
                    "puntos"
                ],
                "summary": "Elimina un punto de donación",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Punto de Donación",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Punto de donación eliminado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Punto de donación no encontrado",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/puntosDB": {
            "get": {
                "description": "Obtiene todos los puntos de donación recomendados por la ONG.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "puntos"
                ],
                "summary": "Obtiene todos los puntos de donación recomendados.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.PuntoDeDonacion"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.PuntoDeDonacion": {
            "type": "object",
            "properties": {
                "ciudad": {
                    "type": "string"
                },
                "coordenadas": {
                    "description": "Coordenadas en formato WKT",
                    "type": "string"
                },
                "direccion": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nombre": {
                    "type": "string"
                }
            }
        },
        "routes.PuntoDeDonacionResult": {
            "type": "object",
            "properties": {
                "ciudad": {
                    "type": "string"
                },
                "coordenadas": {
                    "type": "string"
                },
                "direccion": {
                    "type": "string"
                },
                "distancia": {
                    "type": "number"
                },
                "nombre": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Puntos de Donación API",
	Description:      "Esta es una API para gestionar puntos de donación y obtener recomendaciones en base a los mismos.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
